### ISSUE TITLE
Accuracy mismatch between clear and FHE predictions in CIFAR-10 example

### ISSUE THREAD

**Issue by bhuvneshchaturvedi2512** [zama-ai/concrete-ml#380]
I am trying to run the VGG like NN on CIFAR-10 example found at https://github.com/zama-ai/concrete-ml/tree/main/use_case_examples/cifar/cifar_brevitas_training.

When I am running the example once, I am getting correct results in terms of accuracy (during validation) being similar in clear and FHE predictions. However, when I am running the same code multiple times with same parameters, I am getting a huge difference in the accuracy of clear and FHE predictions. For example, in clear prediction I am getting accuracy of around 97%, which remains similar across the multiple iterations. On the other hand, the accuracy in FHE prediction drops to around 40% to 50% and varies in this range across multiple iterations. I am executing the scripts as obtained from the repository, while only changing the number of training epochs to 10 from default 1000.

I am unable to understand why this is happening. While it is understandable that multiple training iterations will result in models with varied accuracy, such significant drop in the accuracy, that too only in FHE prediction, does not make sense to me. Please let me know if any other code base for CIFAR-10 is available or not.

**Comment by RomanBredehoft** [comment]
Hello @bhuvneshchaturvedi2512 ,
Thanks for the report, we were unfortunately not able to reproduce what you seem to explain 😕 Could you therefore give us more information about your issue ? More precisely : 
- are you using one of our latest commit ? if not, would it be possible to do so and try again ? 
- could you provide the specific steps you've followed ? 

For information, in the `cifar_brevitas_training` directory, I've ran `python3 bnn_pynq_train.py --epochs 10 --data ./data --experiments ./experiments`, updated `evaluate_torch_cml.py` with the new `checkpoint` path and then ran `python3 evaluate_torch_cml.py`, which gave me : 
```
Torch accuracy top1: 0.6928401898734177
Concrete ML accuracy top1: 0.6919501582278481
Torch accuracy top5: 0.9740901898734177
Concrete ML accuracy top5: 0.9739912974683544
```

Please tell me if the issue you're describing is different from the above steps !

Thanks 😃

**Comment by bhuvneshchaturvedi2512** [comment]
Hello @RomanBredehoft, thank you for your response.

The current version is working fine and I am getting similar accuracy on multiple reruns of the script. I guess this was a problem with the previous version of the code which I tested in the first week of September. I see the code was updated a month ago, possibly in the third or fourth week of September.

On an additional note, the script evaluation_one_example_fhe.py (which is named evaluate_one_example_fhe.py in the repository but not in the command python3 evaluation_one_example_fhe.py) runs the inference in the encrypted setting which takes around 15 to 20 minutes on my machine. Can you please let me know if it is possible to run the inference in simulation mode? This will make it easy for me to test some of the stuff quickly.

I appreciate your help.

**Comment by RomanBredehoft** [comment]
Hello again @bhuvneshchaturvedi2512 , 
Great to know that it works well ! 

Regarding the `evaluate_one_example_fhe.py` file, thanks for pointing out the typo, I've created a small PR to fix it. As for running the script in simulation, I think the easiest solution for you would be to simply comment all lines starting at [l144 ](https://github.com/zama-ai/concrete-ml/blob/f7c3256c9d2426115e40a39a2e4476c688ac8384/use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py#L144C14-L144C14) and only print the simulated results ( `print(f"Expected prediction: {expected_quantized_prediction}")`, as done in [l171](https://github.com/zama-ai/concrete-ml/blob/f7c3256c9d2426115e40a39a2e4476c688ac8384/use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py#L171) ! This is because simulation is already executed at [l141](https://github.com/zama-ai/concrete-ml/blob/f7c3256c9d2426115e40a39a2e4476c688ac8384/use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py#L141C22-L141C22) 😄 

Quick notes about it : 
- don't forget to `git lfs pull` before if you haven't done so
- by default, this script only runs a single inference ! You can change that by running `NUM_SAMPLES=100 python3 evaluate_one_example_fhe.py` for 100 inferences for example
- you'll need to remove the `FHEModelDev` lines ([l92-93](https://github.com/zama-ai/concrete-ml/blob/f7c3256c9d2426115e40a39a2e4476c688ac8384/use_case_examples/cifar/cifar_brevitas_training/evaluate_one_example_fhe.py#L92)) if you want to execute the script several times (I'll removed them as well as they are not used anymore anyway)

**Comment by bhuvneshchaturvedi2512** [comment]
Hello  @RomanBredehoft, thank you for your prompt response and also for answering my additional query. As for the FHEModelDev lines (l92-93), I have commented them out from my end (thank you for pointing this out though).

I am closing the issue from my end as I do not have any further questions (for now). I genuinely appreciate your help.
